package org.jhipster.acervolivraria.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PosicaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPosicaoAllPropertiesEquals(Posicao expected, Posicao actual) {
        assertPosicaoAutoGeneratedPropertiesEquals(expected, actual);
        assertPosicaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPosicaoAllUpdatablePropertiesEquals(Posicao expected, Posicao actual) {
        assertPosicaoUpdatableFieldsEquals(expected, actual);
        assertPosicaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPosicaoAutoGeneratedPropertiesEquals(Posicao expected, Posicao actual) {
        assertThat(expected)
            .as("Verify Posicao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPosicaoUpdatableFieldsEquals(Posicao expected, Posicao actual) {
        assertThat(expected)
            .as("Verify Posicao relevant properties")
            .satisfies(e -> assertThat(e.getCodigo()).as("check codigo").isEqualTo(actual.getCodigo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPosicaoUpdatableRelationshipsEquals(Posicao expected, Posicao actual) {
        // empty method
    }
}
